# Generated by Django 6.0.2 on 2026-02-25 10:13

import tasks_app.models.category
import tasks_app.models.task
import tasks_app.models.user
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_app', '0002_replace_unique_together_with_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.CharField(default=tasks_app.models.category.category_id_default, editable=False, max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.CharField(default=tasks_app.models.task.task_id_default, editable=False, max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='id',
            field=models.CharField(default=tasks_app.models.user.telegram_user_id_default, editable=False, max_length=20, primary_key=True, serialize=False),
        ),
    ]
